openapi: "3.1.0"
info:
  title: "Sim Sage KYRNL API"
  version: "1.0.0"
  description: "API to retrieve the Sim Sage KYRNL from a Supabase public bucket"
servers:
  - url: "https://grfheayxwxyseqqbjdwt.supabase.co/storage/v1/object/public/kin-archive"
paths:
  /Sim_Sage_KYRNL_06052025183840.json:
    get:
      operationId: "getKyrnl"
      summary: "Retrieve KYRNL JSON"
      responses:
        "200":
          description: "KYRNL retrieved successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  version:
                    type: string
                  description:
                    type: string
                  components:
                    type: object
