openapi: 3.1.0
info:
  title: Sim Sage KYRNL Retrieval API
  description: API to retrieve the Sim Sage KYRNL for prototype integration.
  version: "1.0.0"
servers:
  - url: https://grfheayxwxyseqqbjdwt.supabase.co/storage/v1/object/public/kin-archive/
paths:
  /Sim_Sage_KYRNL_06052025183840.json:
    get:
      summary: Retrieve the Sim Sage KYRNL JSON
      operationId: getKyrnl
      responses:
  "200":
    description: "KYRNL retrieved successfully"
    content:
      application/json:
        schema:
          type: object
          properties:
            name:
              type: string
            version:
              type: string
            description:
              type: string
            components:
              type: object

                example:
                  status: success
                  message: "KYRNL retrieved"
                  data: { ... }
